# Generated by Django 5.0.1 on 2024-02-16 12:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0002_alter_handbook_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='handbook',
            name='description_ky',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='handbook',
            name='description_uz',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='handbook',
            name='name_ky',
            field=models.CharField(max_length=221, null=True),
        ),
        migrations.AddField(
            model_name='handbook',
            name='name_uz',
            field=models.CharField(max_length=221, null=True),
        ),
        migrations.AddField(
            model_name='handbook',
            name='some_text_ky',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='handbook',
            name='some_text_uz',
            field=models.TextField(blank=True, null=True),
        ),
    ]
