# Generated by Django 5.0.1 on 2024-01-10 07:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_news_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=123)),
                ('price', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=123)),
                ('description', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='tour/')),
            ],
            options={
                'verbose_name': 'Tur',
                'verbose_name_plural': 'Turlar',
            },
        ),
    ]
