# Generated by Django 5.0.1 on 2024-02-16 12:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='content_ky',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='content_uz',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ky',
            field=models.CharField(max_length=333, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_uz',
            field=models.CharField(max_length=333, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='branch_name_ky',
            field=models.CharField(max_length=123, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='branch_name_uz',
            field=models.CharField(max_length=123, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='description_ky',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='description_uz',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='name_ky',
            field=models.CharField(max_length=123, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='name_uz',
            field=models.CharField(max_length=123, null=True),
        ),
    ]
